name: Deploy to Naver Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Naver Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deploy
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /root/Cody-Now/
            sudo git pull origin main
            source venv/bin/activate
            pip3 install -r requirements.txt
            
            # static 디렉토리 설정
            sudo rm -rf staticfiles/*
            sudo mkdir -p staticfiles
            sudo chmod -R 777 staticfiles

            # production 설정으로 collectstatic 실행
            python3 manage.py collectstatic --noinput --settings=config.settings.production
            python3 manage.py migrate --settings=config.settings.production
            
            # 서비스 재시작
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx

      - name: Send Slack notification (Success)
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 *Deploy 성공!* \nBranch: ${{ github.ref }} \nCommit: ${{ github.sha }} \n🟢 서비스가 정상적으로 배포되었습니다!"
          SLACK_COLOR: "#36a64f"

      - name: Send Slack notification (Failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "❌ *Deploy 실패!* \nBranch: ${{ github.ref }} \nCommit: ${{ github.sha }} \n🔴 배포 중 오류가 발생했습니다. 로그를 확인하세요."
          SLACK_COLOR: "#ff0000"